name: websocket-server

services:
  appserver:
    type: node:18
    env_file:
      - .env.local
    run:
      cmd: yarn run dev
      webroot: /app
    build:
      cmd: yarn install
  websocket:
    type: php:8.2
    port: 8080
    run:
      cmd: php websocket-server.php
proxy:
  appserver:
    - websocket-server.lndo.site
    - websocket-server.lndo.site:3000
  websocket:
    - websocket-server.lndo.site:8080

tooling:
  watch:
    service: appserver
    cmd: yarn run dev
  build:
    service: appserver
    cmd: yarn run build && yarn run start
  websocket:
    service: websocket
    cmd: php websocket-server.php
